### ISSUE TITLE
record flow of traffic in a time period

### ISSUE THREAD

**Issue by kykyfilu** [movsim/traffic-simulation-de#14]
Hello Dr. Treiber,

I'm working on a project and was wondering if there was a way to record the flow of traffic at the detectors. 

I would like to record the flow value every 60 seconds for an hour to give me 60 data points that I require for my investigation.

Is there any way to do this automatically, as opposed to manually noting the flow at the specific times?

I will of course credit <traffic-simulation.de> in my work.

Kind Regards

**Comment by MTGermany** [comment]
I have implemented the functionality. Just click on the blue download button to start recording, and click again to end it. Notice that the aggregation time interval is 10 s. If you want minute-averages, just do an arithmetic average of the flow in 6-blocks and a flow-weighted arithmetic average for the speeds
