### ISSUE TITLE
strange slow down with latest EDGE browser

### ISSUE THREAD

**Issue by rs38** [movsim/traffic-simulation-de#15]
Microsoft Edge
Version 98.0.1108.50 (Official build) (64-bit)

traffic animation slows down like extreme slow mo with 1-2 fps.

With Chrome all works smooth.

**Comment by MTGermany** [comment]
As a Linux user, I have no access to Microsoft Edge. I tested in on BrowserStack (free plan) with Edge 98 (they did no further distinction) and it worked correctly. I also tested it on browserling.com and could reproduce your observation. Did you encounter similar problems with former versions of the MS browsers?

**Comment by MTGermany** [comment]
A possible cause could be the new "Super Duper Secure Mode" of the newest Edge variants. In order to test that, check if this mode is turned on by entering edge://flag into the URL line of Edge, then enter "Super Duper Secure Mode"

**Comment by rs38** [comment]
my Edge does not know any super duper mode. So I couldn't disable it.
Now checked on different machines, all fine except my Notebook, where I recently activated a kind of battery saving mode which caused the slowness after a few seconds.
Sorry for that, simply my setting was screwed and you pointed me to the right direction.
