### ISSUE TITLE
Slider default "value" vs. "position" default mismatch

### ISSUE THREAD

**Issue by begincalendar** [movsim/traffic-simulation-de#2]
Sliders have a default "position" to the far left, but their default "value" does not always correspond to the minimum possible value that slider can take.
E.g. On the "Ringroad" simulation, the "Timewarp" slider position defaults to the far left, but the default "value" is "8 times", even though the minimum "value" is "0.1 times".

This produces a sub-par UX in my opinion, where the solution should be that the "value" and "position" of the sliders are always in sync and not just after the slider has been moved.

**Comment by MTGermany** [comment]
Hi Matt,this will be corrected at the next major  version which is nearly finished (I replaced the external library-based sliders by generic html5 sliders). IThis version also introduces a lot of new user interactions such as  road and vehicle moving, obstacle dropping etc Martin
Matt <notifications@github.com> hat am 23. Juni 2017 um 03:05 geschrieben:Sliders have a default "position" to the far left, but their default "value" does not always correspond to the minimum possible value that slider can take.
E.g. On the "Ringroad" simulation, the "Timewarp" slider position defaults to the far left, but the default "value" is "8 times", even though the minimum "value" is "0.1 times".
This produces a sub-par UX in my opinion, where the solution should be that the "value" and "position" of the sliders are always in sync and not just after the slider has been moved.
