### ISSUE TITLE
Modify simulation interval dt

### ISSUE THREAD

**Issue by theone95cn** [movsim/traffic-simulation-de#25]
This is indeed a great thing.
I want to use this simulation of stop and go traffic waves to obtain the trajectory of vehicles, but I found that the output trajectory interval is not regular (dt fluctuates between 0.67 and 1.33). I want to obtain an interval dt of 0.01, how to set it?

**Comment by MTGermany** [comment]
The output trajectory time interval is set by the variable dt_export=1;  in gui.js. However, this does not give the realized timestep if the output time step is not a multiple of the simulation time step. During the simulation, a time counter runs and triggers a trajectory data point to be stored one the cumulated time is greater than dt_export. Then, the trajectory data point is stored and the counter decremented by dt_export. So, the output time interval is always a multiple of the simulation time interval, in your case 0.67 s. 

The simulation time interval, in turn, is dynamically set to realize fps=30. Obviously, you had set the timelapse factor to 20, so 20/(30/s)=0.67 s. 

To obtain very low time intervals, e.g., 0.01 s, you need to do the following:

(1) Set dt_export=0.01;  in control_gui.js
(2) Chose the smallest possible time-lapse factor by controlling the sliders in the simulation
(3) Use the normal blue download button

If the resulting time intervals are still not low enough (why do you ned dt=0.01 s?), you can change the  settings of the <td>Timelapse</td> slider in the corresponding html file(s), e.g., min="0.1"

I have also documented this in README.md, now.

**Comment by theone95cn** [comment]
Thank you, following your method, it did do it
