### ISSUE TITLE
Error with Latest download

### ISSUE THREAD

**Issue by Anish-Shrestha** [movsim/traffic-simulation-de#5]
Hi, I have downloaded the latest version of this project and it's giving me an error while running the project. I am researching on traffic-simulation and it would be a great help if you can provide me with the bug-free code. Thanks

**Comment by akegermany** [comment]
Hi. The build is green both for develop (latest version) and master. So, it's perhaps a bit hasty to call for a bug-free code. 

See: https://github.com/movsim/movsim
https://travis-ci.org/movsim/movsim
