### ISSUE TITLE
collecting data 

### ISSUE THREAD

**Issue by FatimaAhmedR** [movsim/traffic-simulation-de#8]
can we collect data (flow and speed) in other files using sublime text?

**Comment by MTGermany** [comment]
Dear FatimaAhmedR,
  
  
   
    
   
   
    I do not know what exactly you want to record. I assume it is the detector readings. Yes, you can record these. Whatever you do with them, it would b nice to mention the source (traffic-simulation.de)
   
   
    Best,
    Martin
   
   
    
    ----------------------------------------------------------
   Dr. Martin Treiber
   Institute for Transport & Economics, TU Dresden
   Chair of Traffic Modelling, Econometrics, and Statistics
   Falkenbrunnen, Room 123 (two floors up from the entrance!)
   Würzburger Str. 35, D-01062 Dresden
   martin@mtreiber.de
   www.mtreiber.de
   phone/fax: +49 (351) 463 36794 / 36809
   ---------------------------------------------------------
   
   
  
  
   FatimaAhmedR <notifications@github.com> hat am 18. November 2019 um 08:39 geschrieben: 
   
   
   can we collect data (flow and speed) in other files using sublime text?

**Comment by MTGermany** [comment]
I have implemented a "download trajectories" functionality (start download " button) resulting in .txt files of all trajectories. There, you can also read off the virtual detector records by determining the passing times and local speeds at passing time  at any chosen detector position
