### ISSUE TITLE
Microsimulation of Traffic flow 

### ISSUE THREAD

**Issue by FatimaAhmedR** [movsim/traffic-simulation-de#9]
can you explain the parameter (Mainroad Perc, Timewarp, Max accel a) 
Thank you ..

**Comment by MTGermany** [comment]
Most of the parameters are explained by repeatedly clicking the context-sensitive blue "i" (information) button. The "Mainroad Perc" is only relevant for the roundabout scenario and controls the percentage of the overall traffic entering the simulation from the main road (the two horizontal arms). With the choicebox and the choices "only straight ahead", "all left turning", "all right turning" or "all directions", you can control the arms where the vehicles leave the roundabout 

 See also the closed issue #12
